[build]
  base    = "winXP"
  command = "npm run build"
  publish = "winXP/build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
